$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
# name: train_yaml

display_name: mask2former_swing_tiny_cracks_augmentation
experiment_name: mask2former_tfm_train
description: Train defect model for 19-02-26 dataset with augmentation with crack classes (not joined)and pretrained weights from the base model

# invoke completions (Ctrl+Space, Cmd+Space) to see the list of computes available
compute: azureml:MODELTRAINING
# This defines the input data to mount. The names of the items in inputs can be referenced in the command
inputs:
  input_dataset:
    type: uri_folder
    path: azureml:laura_tfm_defect_data@latest #(latest = v5)
    mode: ro_mount
  pretrained_weights:
    type: uri_file
    path: azureml:mask2former_swin_tiny_512x512_base_model@latest
    mode: ro_mount
  labels_folder: "labels_cracks"


outputs:
  output_path:
    type: uri_folder
    path: azureml://datastores/workspaceblobstore/paths/checkpoints/mask2former_swing-tiny_cracks_augmentation
    mode: rw_mount

code: "../../"

# change this to run my training
command: >-
  python3 scripts/azure/train_mask2former.py  
  --config configs/azure/cracks_augmentation.py
  --data_root ${{inputs.input_dataset}} 
  --labels_folder ${{inputs.labels_folder}}
  --weights ${{inputs.pretrained_weights}}
  --work_dir ${{outputs.output_path}}


environment:
  image: crflowityartifacts.azurecr.io/roadai/laura_tfm:mask2formerSwing 